<?php

namespace Database\Seeders;

use App\Models\Expense;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class ExpensesSeeders extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // 'title',
        // 'description',
        // 'total',
        // 'date',
        // 'status',
        // 'category_of_expense_id',
        // 'user_id',
        // 'office_id',
       
        $expenses = [
            
            [  'title'=>"Gasto". rand(1,20),
                'description'=>'Descripcion del gasto 1',
                'total'=>100,
                'date' => Carbon::now(),
                'category_of_expense_id' => rand(1,8),
                'user_id' => 1,
                'office_id'=> rand(1,2),
        ],
            [  'title'=>"Gasto". rand(1,20),
                'description'=>'Descripcion del gasto 1',
                'total'=>100,
                'date' => Carbon::now(),
                'category_of_expense_id' => rand(1,8),
                'user_id' => 1,
                'office_id'=> rand(1,2),
        ],
            [  'title'=>"Gasto". rand(1,20),
                'description'=>'Descripcion del gasto 1',
                'total'=>100,
                'date' => Carbon::now(),
                'category_of_expense_id' => rand(1,8),
                'user_id' => 1,
                'office_id'=> rand(1,2),
        ],
            [  'title'=>"Gasto". rand(1,20),
                'description'=>'Descripcion del gasto 1',
                'total'=>100,
                'date' => Carbon::now(),
                'category_of_expense_id' => rand(1,8),
                'user_id' => 1,
                'office_id'=> rand(1,2),
        ],
            [  'title'=>"Gasto". rand(1,20),
                'description'=>'Descripcion del gasto 1',
                'total'=>100,
                'date' => Carbon::now(),
                'category_of_expense_id' => rand(1,8),
                'user_id' => 1,
                'office_id'=> rand(1,2),
        ],
            [  'title'=>"Gasto". rand(1,20),
                'description'=>'Descripcion del gasto 1',
                'total'=>100,
                'date' => Carbon::now(),
                'category_of_expense_id' => rand(1,8),
                'user_id' => 1,
                'office_id'=> rand(1,2),
        ],
            [  'title'=>"Gasto". rand(1,20),
                'description'=>'Descripcion del gasto 1',
                'total'=>100,
                'date' => Carbon::now(),
                'category_of_expense_id' => rand(1,8),
                'user_id' => 1,
                'office_id'=> rand(1,2),
        ],
            [  'title'=>"Gasto". rand(1,20),
                'description'=>'Descripcion del gasto 1',
                'total'=>100,
                'date' => Carbon::now(),
                'category_of_expense_id' => rand(1,8),
                'user_id' => 1,
                'office_id'=> rand(1,2),
        ],
            [  'title'=>"Gasto". rand(1,20),
                'description'=>'Descripcion del gasto 1',
                'total'=>100,
                'date' => Carbon::now(),
                'category_of_expense_id' => rand(1,8),
                'user_id' => 1,
                'office_id'=> rand(1,2),
        ],
            [  'title'=>"Gasto". rand(1,20),
                'description'=>'Descripcion del gasto 1',
                'total'=>100,
                'date' => Carbon::now(),
                'category_of_expense_id' => rand(1,8),
                'user_id' => 1,
                'office_id'=> rand(1,2),
        ],
            [  'title'=>"Gasto". rand(1,20),
                'description'=>'Descripcion del gasto 1',
                'total'=>100,
                'date' => Carbon::now(),
                'category_of_expense_id' => rand(1,8),
                'user_id' => 1,
                'office_id'=> rand(1,2),
        ],
            [  'title'=>"Gasto". rand(1,20),
                'description'=>'Descripcion del gasto 1',
                'total'=>100,
                'date' => Carbon::now(),
                'category_of_expense_id' => rand(1,8),
                'user_id' => 1,
                'office_id'=> rand(1,2),
        ],
            [  'title'=>"Gasto". rand(1,20),
                'description'=>'Descripcion del gasto 1',
                'total'=>100,
                'date' => Carbon::now(),
                'category_of_expense_id' => rand(1,8),
                'user_id' => 1,
                'office_id'=> rand(1,2),
        ],
            [  'title'=>"Gasto". rand(1,20),
                'description'=>'Descripcion del gasto 1',
                'total'=>100,
                'date' => Carbon::now(),
                'category_of_expense_id' => rand(1,8),
                'user_id' => 1,
                'office_id'=> rand(1,2),
        ],
            [  'title'=>"Gasto". rand(1,20),
                'description'=>'Descripcion del gasto 1',
                'total'=>100,
                'date' => Carbon::now(),
                'category_of_expense_id' => rand(1,8),
                'user_id' => 1,
                'office_id'=> rand(1,2),
        ],
            [  'title'=>"Gasto". rand(1,20),
                'description'=>'Descripcion del gasto 1',
                'total'=>100,
                'date' => Carbon::now(),
                'category_of_expense_id' => rand(1,8),
                'user_id' => 1,
                'office_id'=> rand(1,2),
        ],
            [  'title'=>"Gasto". rand(1,20),
                'description'=>'Descripcion del gasto 1',
                'total'=>100,
                'date' => Carbon::now(),
                'category_of_expense_id' => rand(1,8),
                'user_id' => 1,
                'office_id'=> rand(1,2),
        ],
            [  'title'=>"Gasto". rand(1,20),
                'description'=>'Descripcion del gasto 1',
                'total'=>100,
                'date' => Carbon::now(),
                'category_of_expense_id' => rand(1,8),
                'user_id' => 1,
                'office_id'=> rand(1,2),
        ],
            [  'title'=>"Gasto". rand(1,20),
                'description'=>'Descripcion del gasto 1',
                'total'=>100,
                'date' => Carbon::now(),
                'category_of_expense_id' => rand(1,8),
                'user_id' => 1,
                'office_id'=> rand(1,2),
        ],
            [  'title'=>"Gasto". rand(1,20),
                'description'=>'Descripcion del gasto 1',
                'total'=>100,
                'date' => Carbon::now(),
                'category_of_expense_id' => rand(1,8),
                'user_id' => 1,
                'office_id'=> rand(1,2),
        ],
        ];

        foreach ($expenses as $expense) {
            Expense::create($expense);
        }
    }
}
